### ISSUE TITLE
ansible-cowried: Port redirection

### ISSUE THREAD

**Issue by it-kombinat** [it-kombinat/splunk-demo#10]
- Add additional port in the sec_group for ec2
- Configure SSHD on Cowrie host to use different SSH port (extra play)
- next play is to use this port to configure cowrie and the other stuff ...

```
- name: Installing Snort and Docker Collector
  hosts: snort
  become: true
  remote_user: ec2-user
  remote_port: 23
  tags: snort
  vars:
  ....

```

```
iptables -t nat -A PREROUTING -p tcp --dport 22 -j REDIRECT --to-port 2222
```
